version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: 12345
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "system/${ORACLE_PWD}@//localhost:1521/FREE", "@healthcheck.sql" ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: "2g"